"""
nexus-useful-data-source-for-agents-doing-prod — LangChain Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.langchain_tool import rank_buywhere_products_by_value_score_tool, fetch_buywhere_vendor_price_distribution_tool, resolve_buywhere_product_identity_tool, compare_buywhere_products_causal_rank_tool, extract_buywhere_deal_anomalies_tool
    agent = initialize_agent([rank_buywhere_products_by_value_score_tool, fetch_buywhere_vendor_price_distribution_tool, resolve_buywhere_product_identity_tool, compare_buywhere_products_causal_rank_tool, extract_buywhere_deal_anomalies_tool], llm,
                              agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)
"""

from typing import Any
from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class RankBuywhereProductsByValueScoreInput(BaseModel):
    query: str = Field(..., description="Natural-language product description, e.g. 'noise-cancelling wireless headphones under SGD 300'. Must be in English.")
    top_k: float = Field(None, description='Maximum number of ranked products to return. Higher values increase latency. Recommended 5-20 for agent consumption.')
    max_price_sgd: float = Field(None, description='Hard upper bound on product price in SGD. Products strictly above this value are excluded before ranking. Set to null to disable.')
    category_filter: str = Field(None, description="BuyWhere top-level category slug to restrict the search scope, e.g. 'electronics', 'home-appliances', 'health-beauty'. Leave null for cross-category search.")


def _rank_buywhere_products_by_value_score_impl(query, top_k, max_price_sgd, category_filter) -> Any:
    return call_mcp_tool("nexus_useful_data_source_for_agents_doing_prod_rank_buywhere_products_by_value_score", {"query": query, "top_k": top_k, "max_price_sgd": max_price_sgd, "category_filter": category_filter})


rank_buywhere_products_by_value_score_tool = StructuredTool.from_function(
    func=_rank_buywhere_products_by_value_score_impl,
    name="nexus_useful_data_source_for_agents_doing_prod_rank_buywhere_products_by_value_score",
    description="Searches the BuyWhere Singapore catalogue for products matching a natural-language query and returns them ranked by an auditable value-score derived from information-theoretic entropy of cross-vendor price variance. Use this when an agent needs to compare multiple products across vendors and justify a recommendation beyond lowest-price. Do NOT use for exact SKU or model-number lookups where identity matters more than value ranking, and do NOT use when the agent needs only a single vendor's listing.",
    args_schema=RankBuywhereProductsByValueScoreInput,
)

class FetchBuywhereVendorPriceDistributionInput(BaseModel):
    product_id: str = Field(..., description='BuyWhere internal product identifier as returned by rank_buywhere_products_by_value_score or resolve_buywhere_product_identity. Format: alphanumeric string.')
    include_out_of_stock: bool = Field(None, description='If true, vendors with current stock_status=out_of_stock are included in the distribution for historical completeness. If false, only in-stock vendors are used. Default false to reflect actionable prices.')


def _fetch_buywhere_vendor_price_distribution_impl(product_id, include_out_of_stock) -> Any:
    return call_mcp_tool("nexus_useful_data_source_for_agents_doing_prod_fetch_buywhere_vendor_price_distribution", {"product_id": product_id, "include_out_of_stock": include_out_of_stock})


fetch_buywhere_vendor_price_distribution_tool = StructuredTool.from_function(
    func=_fetch_buywhere_vendor_price_distribution_impl,
    name="nexus_useful_data_source_for_agents_doing_prod_fetch_buywhere_vendor_price_distribution",
    description='Given a BuyWhere product identifier, returns the full cross-vendor price distribution in SGD along with the Shannon entropy of that distribution and a causal price-spread coefficient that quantifies whether price differences are driven by vendor margin or by product condition/variant. Use this when an agent already knows the product and needs to audit price fairness or detect outlier vendor pricing. Do NOT use as a discovery tool — it requires a known BuyWhere product_id. Do NOT use when only the cheapest vendor matters and no justification is needed.',
    args_schema=FetchBuywhereVendorPriceDistributionInput,
)

class ResolveBuywhereProductIdentityInput(BaseModel):
    raw_product_name: str = Field(..., description="Partial or ambiguous product name, brand + model fragment, or user-typed string. E.g. 'Sony WH-1000' or 'dyson v11 vacuum'.")
    candidate_limit: float = Field(None, description='Number of candidate product identities to return when the match is ambiguous. The agent should surface these to the user if score < 0.90.')


def _resolve_buywhere_product_identity_impl(raw_product_name, candidate_limit) -> Any:
    return call_mcp_tool("nexus_useful_data_source_for_agents_doing_prod_resolve_buywhere_product_identity", {"raw_product_name": raw_product_name, "candidate_limit": candidate_limit})


resolve_buywhere_product_identity_tool = StructuredTool.from_function(
    func=_resolve_buywhere_product_identity_impl,
    name="nexus_useful_data_source_for_agents_doing_prod_resolve_buywhere_product_identity",
    description='Takes an ambiguous product name or partial model number and returns the canonical BuyWhere product_id with a semantic similarity score and disambiguation metadata. Use this before calling fetch_buywhere_vendor_price_distribution when the agent has a user-supplied name that may match multiple listings. Do NOT use when the agent already holds a validated product_id from a previous tool call — redundant resolution adds latency. Do NOT use for open-ended exploratory queries; use rank_buywhere_products_by_value_score instead.',
    args_schema=ResolveBuywhereProductIdentityInput,
)

class CompareBuywhereProductsCausalRankInput(BaseModel):
    product_ids: list[str] = Field(..., description='List of BuyWhere product identifiers to compare. Must contain between 2 and 10 items. Order does not affect output ranking.')
    adjustment_covariates: list[str] = Field(None, description="Confounders to adjust for in the causal model. Accepted values: 'brand_premium', 'vendor_count_bias', 'recency_bias', 'condition_variant'. Defaults to all four if omitted.")


def _compare_buywhere_products_causal_rank_impl(product_ids, adjustment_covariates) -> Any:
    return call_mcp_tool("nexus_useful_data_source_for_agents_doing_prod_compare_buywhere_products_causal_rank", {"product_ids": product_ids, "adjustment_covariates": adjustment_covariates})


compare_buywhere_products_causal_rank_tool = StructuredTool.from_function(
    func=_compare_buywhere_products_causal_rank_impl,
    name="nexus_useful_data_source_for_agents_doing_prod_compare_buywhere_products_causal_rank",
    description='Accepts a list of BuyWhere product_ids and returns a causal ranking that controls for confounders (brand premium, recency bias, vendor count asymmetry) using do-calculus-inspired adjustment on the value-score. Use this when an agent has a shortlist of 2-10 products and needs a defensible recommendation that is not contaminated by spurious correlations. Do NOT use with more than 10 products — use rank_buywhere_products_by_value_score for larger candidate sets. Do NOT use when the comparison must be within a single vendor.',
    args_schema=CompareBuywhereProductsCausalRankInput,
)

class ExtractBuywhereDealAnomaliesInput(BaseModel):
    query_or_category: str = Field(..., description='Either a natural-language product query or a BuyWhere category slug. The tool resolves which interpretation applies based on format.')
    z_score_threshold: float = Field(None, description='Minimum absolute z-score (relative to category price distribution) for a listing to be classified as anomalous. Lower values return more candidates with lower confidence; higher values return fewer with higher confidence. Typical useful range 1.5-3.0.')
    anomaly_types: list[str] = Field(None, description="Filter output to specific anomaly classifications. Accepted values: 'price_too_low', 'price_too_high', 'vendor_outlier', 'possible_data_error'. Defaults to all types if omitted.")


def _extract_buywhere_deal_anomalies_impl(query_or_category, z_score_threshold, anomaly_types) -> Any:
    return call_mcp_tool("nexus_useful_data_source_for_agents_doing_prod_extract_buywhere_deal_anomalies", {"query_or_category": query_or_category, "z_score_threshold": z_score_threshold, "anomaly_types": anomaly_types})


extract_buywhere_deal_anomalies_tool = StructuredTool.from_function(
    func=_extract_buywhere_deal_anomalies_impl,
    name="nexus_useful_data_source_for_agents_doing_prod_extract_buywhere_deal_anomalies",
    description='Scans a BuyWhere category or query result for listings whose price deviates significantly from the expected distribution (z-score threshold configurable) and flags them as anomalies — potential flash sales, data errors, or grey-market listings. Returns anomaly type classification and confidence. Use this when an agent is doing price-monitoring or deal-hunting on behalf of a user. Do NOT use as a general ranking tool — anomalies are not always good deals (errors and grey-market items are also flagged). Do NOT call on product_ids already confirmed as anomalies in the same session.',
    args_schema=ExtractBuywhereDealAnomaliesInput,
)