"""
nexus-useful-data-source-for-agents-doing-prod — LangChain Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.langchain_tool import compare_buywhere_vendor_prices_tool, resolve_buywhere_product_catalog_tool, fetch_buywhere_sgd_price_history_tool, detect_buywhere_price_anomalies_tool, rank_buywhere_vendors_by_availability_adjusted_value_tool
    agent = initialize_agent([compare_buywhere_vendor_prices_tool, resolve_buywhere_product_catalog_tool, fetch_buywhere_sgd_price_history_tool, detect_buywhere_price_anomalies_tool, rank_buywhere_vendors_by_availability_adjusted_value_tool], llm,
                              agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)
"""

from typing import Any
from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class CompareBuywhereVendorPricesInput(BaseModel):
    product_id: str = Field(..., description="Canonical BuyWhere product identifier (e.g. 'bw-sg-12345'). Must be obtained from resolve_buywhere_product_catalog before calling this tool.")
    availability_filter: str = Field(None, description="Filter vendors by fulfillment type. Accepted values: 'online_only', 'physical_only', 'all'. Defaults to 'all'.")
    include_out_of_stock: bool = Field(None, description='If true, includes vendors with zero stock in the response. Useful for historical context but not for purchase decisions.')


def _compare_buywhere_vendor_prices_impl(product_id, availability_filter, include_out_of_stock) -> Any:
    return call_mcp_tool("nexus_useful_data_source_for_agents_doing_prod_compare_buywhere_vendor_prices", {"product_id": product_id, "availability_filter": availability_filter, "include_out_of_stock": include_out_of_stock})


compare_buywhere_vendor_prices_tool = StructuredTool.from_function(
    func=_compare_buywhere_vendor_prices_impl,
    name="nexus_useful_data_source_for_agents_doing_prod_compare_buywhere_vendor_prices",
    description='Fetches live multi-vendor price listings for a specific product from BuyWhere Singapore and returns a unified schema with vendor name, SGD price, stock status (physical store vs online), and an information-theoretic price dispersion score (Shannon entropy over normalized price distribution) to surface anomalies. Use when an agent needs to find the cheapest available option for a known product across vendors. Do NOT use for broad category discovery or when the product name is ambiguous — use resolve_buywhere_product_catalog first to obtain a canonical product_id.',
    args_schema=CompareBuywhereVendorPricesInput,
)

class ResolveBuywhereProductCatalogInput(BaseModel):
    query: str = Field(..., description="Natural-language or keyword product query (e.g. 'Samsung 65 inch QLED TV 2024'). Must be specific enough to narrow results to a single product model.")
    domain: str = Field(..., description="Product domain to scope the search. Accepted values: 'electronics', 'appliances', 'computing'. Narrows index and improves ranking accuracy.")
    max_results: float = Field(None, description='Maximum number of catalog candidates to return. Increase only when the query is known to be ambiguous and the agent needs to present options.')


def _resolve_buywhere_product_catalog_impl(query, domain, max_results) -> Any:
    return call_mcp_tool("nexus_useful_data_source_for_agents_doing_prod_resolve_buywhere_product_catalog", {"query": query, "domain": domain, "max_results": max_results})


resolve_buywhere_product_catalog_tool = StructuredTool.from_function(
    func=_resolve_buywhere_product_catalog_impl,
    name="nexus_useful_data_source_for_agents_doing_prod_resolve_buywhere_product_catalog",
    description='Searches the BuyWhere Singapore catalog by natural-language query or partial product name within a given domain (electronics, appliances, computing) and returns ranked canonical product records including product_id, normalized title, brand, and model number. Use this as the mandatory first step before calling compare_buywhere_vendor_prices or fetch_buywhere_sgd_price_history. Do NOT use if you already hold a valid product_id — it adds unnecessary latency and cost.',
    args_schema=ResolveBuywhereProductCatalogInput,
)

class FetchBuywhereSgdPriceHistoryInput(BaseModel):
    product_id: str = Field(..., description='Canonical BuyWhere product identifier. Obtain from resolve_buywhere_product_catalog.')
    window_days: float = Field(None, description='Number of calendar days of price history to retrieve, counting backwards from today. Minimum 7 for meaningful trend detection; maximum 365.')
    vendor_ids: list[str] = Field(None, description='Optional list of vendor identifiers to restrict history to specific vendors. If omitted, all vendors with recorded prices are included.')


def _fetch_buywhere_sgd_price_history_impl(product_id, window_days, vendor_ids) -> Any:
    return call_mcp_tool("nexus_useful_data_source_for_agents_doing_prod_fetch_buywhere_sgd_price_history", {"product_id": product_id, "window_days": window_days, "vendor_ids": vendor_ids})


fetch_buywhere_sgd_price_history_tool = StructuredTool.from_function(
    func=_fetch_buywhere_sgd_price_history_impl,
    name="nexus_useful_data_source_for_agents_doing_prod_fetch_buywhere_sgd_price_history",
    description='Returns time-series price history in SGD for a specific product across all tracked vendors over a requested window. Each data point includes date, vendor_id, price_sgd, and availability_type. Also returns a monotone trend coefficient and volatility metric (coefficient of variation) computed over the window. Use when an agent needs to determine if current prices are high or low relative to recent history, or to detect promotional cycles. Do NOT use for real-time best-price comparison — use compare_buywhere_vendor_prices for that. Requires a valid product_id.',
    args_schema=FetchBuywhereSgdPriceHistoryInput,
)

class DetectBuywherePriceAnomaliesInput(BaseModel):
    product_id: str = Field(..., description='Canonical BuyWhere product identifier.')
    anomaly_sensitivity: float = Field(None, description='Z-score threshold above which a vendor price is flagged as anomalous. Lower values increase sensitivity (more flags); higher values reduce false positives. Recommended range 1.5 to 3.0.')
    availability_filter: str = Field(None, description="Restrict anomaly detection to a fulfillment type. Accepted values: 'online_only', 'physical_only', 'all'.")


def _detect_buywhere_price_anomalies_impl(product_id, anomaly_sensitivity, availability_filter) -> Any:
    return call_mcp_tool("nexus_useful_data_source_for_agents_doing_prod_detect_buywhere_price_anomalies", {"product_id": product_id, "anomaly_sensitivity": anomaly_sensitivity, "availability_filter": availability_filter})


detect_buywhere_price_anomalies_tool = StructuredTool.from_function(
    func=_detect_buywhere_price_anomalies_impl,
    name="nexus_useful_data_source_for_agents_doing_prod_detect_buywhere_price_anomalies",
    description="Applies information-theoretic analysis (KL divergence of each vendor price against the market price distribution, combined with z-score outlier detection) to identify vendors whose current SGD price deviates anomalously from the market consensus for a given product. Returns a ranked list of anomalous vendors with deviation direction (unusually cheap vs unusually expensive), confidence score, and a plausible cause flag (e.g. 'clearance', 'bundle_mislisting', 'data_error'). Use when the agent suspects a price is too good or too bad to be real, or when making a high-value purchase decision that warrants anomaly validation. Do NOT use as a substitute for compare_buywhere_vendor_prices — this tool adds analytical overhead and should only be invoked after raw prices are known.",
    args_schema=DetectBuywherePriceAnomaliesInput,
)

class RankBuywhereVendorsByAvailabilityAdjustedValueInput(BaseModel):
    product_id: str = Field(..., description='Canonical BuyWhere product identifier.')
    price_weight: float = Field(None, description='Weight assigned to price in the composite score (0.0 to 1.0). Remaining weight is split between stock reliability and locality. Must sum to 1.0 with availability_weight.')
    availability_weight: float = Field(None, description='Weight assigned to stock availability and fulfillment speed (0.0 to 1.0). Must sum to 1.0 with price_weight.')
    physical_store_proximity_km: float = Field(None, description="Optional. User's distance in km from central Singapore reference point (1.3521 N, 103.8198 E). When provided, physical vendors within 10 km receive a locality bonus in scoring. Omit if delivery preference is irrelevant.")
    top_n: float = Field(None, description='Number of top-ranked vendors to return. Typically 3 is sufficient for a recommendation; increase only if the agent needs to present alternatives.')


def _rank_buywhere_vendors_by_availability_adjusted_value_impl(product_id, price_weight, availability_weight, physical_store_proximity_km, top_n) -> Any:
    return call_mcp_tool("nexus_useful_data_source_for_agents_doing_prod_rank_buywhere_vendors_by_availability_adjusted_value", {"product_id": product_id, "price_weight": price_weight, "availability_weight": availability_weight, "physical_store_proximity_km": physical_store_proximity_km, "top_n": top_n})


rank_buywhere_vendors_by_availability_adjusted_value_tool = StructuredTool.from_function(
    func=_rank_buywhere_vendors_by_availability_adjusted_value_impl,
    name="nexus_useful_data_source_for_agents_doing_prod_rank_buywhere_vendors_by_availability_adjusted_value",
    description="Produces a ranked vendor list for a product that jointly optimizes SGD price and fulfillment preference using a configurable weighted scoring model. Score combines normalized inverse price, in-stock probability (derived from recent stock-status history), and a locality bonus if physical_store_proximity_km is provided. Returns each vendor's composite score, rank, price_sgd, fulfillment_type, and estimated_delivery_days where known. Use when the agent must recommend a single vendor that balances cost and practical availability (e.g. user needs item today vs willing to wait for cheapest online deal). Do NOT use when the agent only needs raw price data without availability weighting — compare_buywhere_vendor_prices is cheaper for that use case.",
    args_schema=RankBuywhereVendorsByAvailabilityAdjustedValueInput,
)